import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Sidebar = {
  "/codex-cli/": [
    {
      text: "Code80 接入 Codex",
      collapsed: false,
      items: [
        { text: "Code80 使用文档", link: "/code80/" },
        { text: "注册账号", link: "/code80/register/1-register" },
        { text: "Codex配置", link: "/code80/cli/3-codex" },
        { text: "CC-Switch", link: "/code80/ccswitch/" },
        { text: "ChatGPT 接入", link: "/code80/ccswitch/6-codex-app" },
        { text: "Codex FAQ", link: "/code80/faq/Codex" },
      ],
    },
    { text: "Codex CLI", items: [
      { text: "首页", link: "/codex-cli/" },
      { text: "你还在等官方插件？OpenAI Codex 接进 IntelliJ，这事到 2025 年还是得“曲线救国”", link: "/codex-cli/2026-03-26-5ec60d-你还在等官方插件-OpenAI-Codex-接进-IntelliJ-这事到-2025-年还是得-曲线救国" },
      { text: "AI编程一站式导航上线了", link: "/codex-cli/2026-04-02-2a8b66-Codex-免费使用指南-2026" },
      { text: "卡在终端里的 AI 编程，终于有人写明白了：Codex CLI 从安装到双 AI 联动，一篇带你上手", link: "/codex-cli/2026-04-02-5b0ddd-复杂-Bug-交给-Codex-日常执行-交给-Claude-这套双-AI-工作流开始成型了" },
      { text: "不想为 Codex 再单独掏钱？这 4 种用法，能把成本压到最低", link: "/codex-cli/2026-04-02-8b0f2c-30秒装好10行命令开干-Codex-CLI-正在把终端写代码变成普通人的默认选项" },
      { text: "Codex 国内怎么用才省事：从官方账号到 Code80 CLI，一篇讲清楚稳定玩法", link: "/codex-cli/2026-04-02-9db5b9-Codex-国内怎么用才省事-官方账号到-Code80-CLI-一篇讲清楚稳定玩法" },
      { text: "从盯终端到指挥多 Agent：Codex 桌面版把 AI 编程推向“值班模式”", link: "/codex-cli/2026-04-13-390b28-从盯终端到指挥多Agent-Codex桌面版把AI编程推向值班模式" },
      { text: "不切终端也能跑 Claude Code：这个 IDEA 插件把 Codex 也一起塞进来了", link: "/codex-cli/2026-04-22-2cc5c7-不切终端也能跑-Claude-Code-这个IDEA插件把Codex也一起塞进来了" },
      { text: "快收藏，油管大佬的Codex入门指南！Vibe Coding必看", link: "/codex-cli/2026-04-22-578cd3-快收藏-油管大佬的Codex入门指南-Vibe-Coding必看" },
      { text: "Claude 封号限流砍权益，OpenAI 趁机用 Codex 稳稳接住你", link: "/codex-cli/2026-04-22-6c39c9-Claude-收紧-Claude-Code-权限后-Codex-为何突然加速-从-Computer-Use-到-Chronicle-的正面对冲" },
      { text: "奥特曼：Codex 正在经历 ChatGPT 时刻。这是要起飞了", link: "/codex-cli/2026-05-03-e7d64a-Codex正在变成你的电脑分身-OpenAI这次把Agent做对了" },
      { text: "2026最新国内使用Claudecode、Codex快速入门小白教程！", link: "/codex-cli/2026-05-05-068937-保姆级教程-通过GACCode在国内使用Claudecode、Codex！" },
      { text: "codex国内编码远超claudecode，2026最新Codex国内保姆级入门教程", link: "/codex-cli/2026-05-05-11d10e-Codex-保姆级入门教程（6000字长文）" },
      { text: "编码能力超越ClaudeCode，最新国内用户一键接入Codex小白快速入门教程", link: "/codex-cli/2026-05-05-8ced81-Codex-保姆级入门教程（6000字长文）" },
      { text: "保姆级教程，快速在国内使用Claudecode、Codex！", link: "/codex-cli/2026-05-05-fc483d-保姆级教程-通过GACCode在国内使用Claudecode、Codex！" },
      { text: "Codex Chrome 插件实测 多标签并行后 AI浏览器代理终于顺手了", link: "/codex-cli/2026-05-08-e4ba2b-Codex-Chrome-插件实测-多标签并行后-AI浏览器代理终于顺手了" },
      { text: "Codex 安装与使用", link: "/codex-cli/2026-05-14-453894-Codex-安装与使用-从网页到CLI把五种入口一次配明白" },
      { text: "OpenAI Codex CLI 新手指南：安装、审批模式和项目规则", link: "/codex-cli/2026-05-25-73eb1f-OpenAI-Codex-CLI新手指南-安装审批模式和项目规则" },
      { text: "AI 编程工具 API 配置教程：Trae、Cursor、Claude Code、Codex、Windsurf", link: "/codex-cli/2026-05-25-a3b8b7-AI编程工具API配置教程-Trae-Cursor-Claude-Code-Codex-Windsurf" },
      { text: "Codex CLI 国内使用教程：从安装到第一个任务", link: "/codex-cli/2026-05-25-cdacfd-Codex-CLI国内使用教程-从安装到第一个任务" },
      { text: "Codex CLI 安装失败排查指南：五类报错一次解决", link: "/codex-cli/2026-05-25-d378a3-Codex-CLI安装失败排查指南-五类报错一次解决" },
      { text: "国内配置 OpenAI Codex CLI 完整指南", link: "/codex-cli/2026-05-25-dede5b-国内配置OpenAI-Codex-CLI完整指南" },
      { text: "IDEA 不只接 Claude 和 Codex：本地模型和第三方 API 也能直接用", link: "/codex-cli/2026-05-25-f07318-IDEA不只接Claude和Codex-本地模型和第三方API也能直接用" },
      { text: "你以为 Codex 是个 App，其实 OpenAI 真正想卖的是一个云端编程分身", link: "/codex-cli/2026-05-31-a47f62-你以为Codex是个App-其实OpenAI真正想卖的是一个云端编程分身" },
      { text: "（2026年最新）Codex CLI 国内使用全攻略：终端 + VSCode + Cursor + Opencode 四种姿势全搞定", link: "/codex-cli/README" },
    ] },
  ],
  "/codex-domestic/": [
    {
      text: "Code80 国内接入",
      collapsed: false,
      items: [
        { text: "快速开始", link: "/code80/" },
        { text: "注册账号", link: "/code80/register/1-register" },
        { text: "购买额度", link: "/code80/register/3-quota" },
        { text: "创建 API 令牌", link: "/code80/register/4-token" },
        { text: "令牌分组介绍", link: "/code80/token/2-group" },
      ],
    },
    { text: "Codex 国内使用", items: [
      { text: "首页", link: "/codex-domestic/" },
      { text: "不想为 Codex 再单独掏钱？这 4 种用法，能把成本压到最低", link: "/codex-domestic/30秒装好10行命令开干-Codex-CLI-正在把终端写代码变成普通人的默认选项" },
      { text: "Codex Chrome 插件实测：多标签并行后，AI 浏览器代理终于顺手了", link: "/codex-domestic/Codex-Chrome-插件实测-多标签并行后-AI浏览器代理终于顺手了" },
      { text: "不想为 Codex 再单独掏钱？这 4 种用法，能把成本压到最低", link: "/codex-domestic/Codex-免费使用指南-2026" },
      { text: "Codex 国内怎么用才省事：从官方账号到 Code80 CLI，一篇讲清楚稳定玩法", link: "/codex-domestic/Codex-国内怎么用才省事-官方账号到-Code80-CLI-一篇讲清楚稳定玩法" },
      { text: "Codex 安装与使用", link: "/codex-domestic/Codex-安装与使用-从网页到CLI把五种入口一次配明白" },
      { text: "不切终端也能跑 Claude Code：这个 IDEA 插件把 Codex 也一起塞进来了", link: "/codex-domestic/不切终端也能跑-Claude-Code-这个IDEA插件把Codex也一起塞进来了" },
      { text: "你还在等官方插件？OpenAI Codex 接进 IntelliJ，这事到 2025 年还是得“曲线救国”", link: "/codex-domestic/你还在等官方插件-OpenAI-Codex-接进-IntelliJ-这事到-2025-年还是得-曲线救国" },
      { text: "codex国内编码远超claudecode，2026最新Codex国内保姆级入门教程", link: "/codex-domestic/小林coding-e287de-Codex 保姆级入门教程（6000字长文）" },
      { text: "编码能力超越ClaudeCode，最新国内用户一键接入Codex小白快速入门教程", link: "/codex-domestic/百度百家号-e1afff-Codex 保姆级入门教程（6000字长文）" },
      { text: "保姆级教程，快速在国内使用Claudecode、Codex！", link: "/codex-domestic/腾讯云开发者社区-540dd7-保姆级教程，通过GACCode在国内使用Claudecode、Codex！" },
      { text: "2026最新国内使用Claudecode、Codex快速入门小白教程！", link: "/codex-domestic/阿里云开发者社区-4111d9-保姆级教程，通过GACCode在国内使用Claudecode、Codex！" },
    ] },
  ],
  "/comparisons/": [
    { text: "Codex 横评", items: [
      { text: "首页", link: "/comparisons/" },
      { text: "DeepSeek V4 Pro 与GPT-5.3 Codex high同台PK，代码能力差距有多大？「一手测试」", link: "/comparisons/2026-04-24-c5fa58-DeepSeek-V4-Pro-与GPT-5.3-Codex-high同台PK-代码能力差距有多大？「一手测试」" },
      { text: "AI 编程工具横评：Claude Code、Cursor、Copilot、Codex 怎么选", link: "/comparisons/2026-05-25-afb457-AI编程工具横评-Claude-Code-Cursor-Copilot-Codex怎么选" },
      { text: "终端 AI Agent 对比：Codex、Claude Code、Hermes、OpenClaw 如何选", link: "/comparisons/2026-05-25-b69d59-终端AI-Agent对比-Codex-ClaudeCode-Hermes-OpenClaw" },
      { text: "同样是 AI 编程，为什么有人越用越快，有人越用越累？", link: "/comparisons/2026-05-31-27b750-你还在纠结Claude-Code和Codex谁更强真正该选的是工作流模式-十万加版" },
      { text: "Cursor 自研模型反超 Opus 4.6：价格直接打到“脚踝”，AI 编程开始拼长期任务了", link: "/comparisons/2026-05-31-4666e1-Cursor自研模型反超Opus-4.6-价格直接打到脚踝-AI编程开始拼长期任务了" },
      { text: "你还在纠结 Claude Code 和 Codex 谁更强？真正该选的是“工作流模式”", link: "/comparisons/2026-05-31-8359f8-你还在纠结-Claude-Code-和-Codex-谁更强-真正该选的是工作流模式" },
      { text: "一天之内两大编程 Agent 同时开卷：GPT-5.3 Codex 和 Claude Opus 4.6，到底谁更值得你押注？", link: "/comparisons/2026-05-31-8b3552-一天之内两大编程-Agent-同时开卷-GPT-5.3-Codex-和-Claude-Opus-4.6-到底谁更值得你押注" },
      { text: "一边写代码一边看视频和 PDF：GPT-5.3 Codex 对上 Gemini 3 Pro，这次该怎么选？", link: "/comparisons/2026-05-31-d3507c-一边写代码一边看视频和-PDF-GPT-5.3-Codex-对上-Gemini-3-Pro-这次该怎么选" },
    ] },
  ],
}
